# Generated by Django 5.2.3 on 2025-07-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_agent', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvanalysisresult',
            name='cv_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
